spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/code_assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-timeout: 20000
      minimum-idle: 2

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: jarvis.email.from@gmail.com
    password: xkhojbxozcysmiwg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

projects:
  base-directory: F:\\Projects

sonar:
  token: squ_60f35502b8270842c5c3e620e0f440038a3a6b09

#spring:
#  config:
#    import: C:\Users\Thanos\Desktop\application.yaml