spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/code_assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-timeout: 20000
      minimum-idle: 2
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: jarvis.email.to@gmail.com
    password: gutuhgtfhobpafgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type,Accept"
  exposed-headers: "Location"

projects:
  base-directory: F:\\Projects

sonar:
  token: squ_9419ed961f6410e3bd558cafb7c9fb0eb72a5a61
  baseUrl: http://localhost:9000/api

thread:
  corePoolSize: 3
  maxPoolSize: 3

#spring:
#  config:
#    import: location to an application.yaml file