package gr.aegean.model.analysis.quality;


public enum QualityAttribute {
    QUALITY,
    COMPREHENSION,
    SIMPLICITY,
    MAINTAINABILITY,
    RELIABILITY,
    COMPLEXITY,
    SECURITY,
    COMMENT_RATE,
    METHOD_SIZE,
    DUPLICATION,
    BUG_SEVERITY,
    TECHNICAL_DEBT_RATIO,
    RELIABILITY_REMEDIATION_EFFORT,
    CYCLOMATIC_COMPLEXITY,
    COGNITIVE_COMPLEXITY,
    VULNERABILITY_SEVERITY,
    HOTSPOT_PRIORITY,
    SECURITY_REMEDIATION_EFFORT
}
